### ISSUE TITLE
How do you install this library?

### ISSUE THREAD

**Issue by Stubbs** [jbboehr/libmustache#6]
I'm trying to create a Homebrew recipe for php-mustache but there's no ./configure script.

How Should I compile & install the lib?

**Comment by jbboehr** [comment]
I'm not particularly familiar with homebrew, but you'll need automake and autoconf to generate the configure script. Differently library, but same principle: https://github.com/jbboehr/handlebars.c#os-x

**Comment by jbboehr** [comment]
Instead of ./bootstrap, you can just use autoreconf -fvi

**Comment by Stubbs** [comment]
Got it, thanks. I'll let you know when they're both available on Homebrew.

**Comment by jbboehr** [comment]
Great, thanks!
